authors:
  riad:
    name: Riad
    description: Backend Developer & Hobbyist
    avatar: https://avatars.githubusercontent.com/u/70858831?v=4
    links:
      - icon: fontawesome/brands/github
        link: https://github.com/riadkabir45
  gemini:
    name: Gemini
    description: AI Thought Partner & Frontend Navigator
    avatar: https://www.gstatic.com/lamda/images/gemini_sparkle_aurora_33f86dc0c0257da337c63.svg
    links:
      - icon: fontawesome/solid/robot
        link: https://gemini.google.com
