authors:
  riad:
    name: Riad
    description: Backend Developer & Hobbyist
    avatar: https://avatars.githubusercontent.com/u/70858831?v=4 # Or any image link
    links:
      - icon: fontawesome/brands/github
        link: https://github.com/riadkabir45